### ISSUE TITLE
LoadError: libmysqlclient_r.so.16: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ektaverma1** [rubypool/tips-errors-challenges#4]
I just upgraded ubuntu from 11.10 to 12.04 and after that when I run test suite or any migrations inside my rails project I got this error: 

/home/ekta/.rvm/gems/ruby-2.0.0-p195/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `require': libmysqlclient_r.so.16: cannot open shared object file: No such file or directory - /home/ekta/.rvm/gems/ruby-2.0.0-p195/gems/mysql2-0.3.18/lib/mysql2/mysql2.so (LoadError)
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195/gems/mysql2-0.3.18/lib/mysql2.rb:31:in`<top (required)>'
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in`block (2 levels) in require'
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in`block in require'
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in`require'
    from /home/ekta/.rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /home/ekta/rcov_test/send_wishes/config/application.rb:7:in`<top (required)>'

---

---

To resolve this error, I just followed the simple steps below: 

`gem uninstall mysql2`

`bundle install`

Or, You can follow these steps : 
`rvm gemset empty <gemset name>`
`gem install bundler`
`bundle install`

It will solve your problem.:pray:

**Comment by segunadeleye** [comment]
I encountered a similar error when I ran `rails server` after I upgraded Ubuntu from 14.04 to 16.04

```
/home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require': libmysqlclient.so.18: cannot open shared object file: No such file or directory - /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.so (LoadError)
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `<top (required)>'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
    from /home/oluwasegun/dd_workspace/dealday/config/application.rb:6:in `<top (required)>'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:79:in `require'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:79:in `block in server'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:76:in `tap'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:76:in `server'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /home/oluwasegun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'
```

The first solution got it fixed.
